language: python
matrix:
  include:
    - python: 2.7
      env:
        - TOX_ENV=py27
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.7
      dist: xenial
      env:
        - TOX_ENV=py37
    - python: pypy
      env:
        - TOX_ENV=pypy
    - python: pypy3
      env:
        - TOX_ENV=pypy3
    - env:
        - TOX_ENV=flake8
    - env:
        - TOX_ENV=docs
    - env:
        - TOX_ENV=coverage
install:
  - sudo apt-get install -y gnupg2 tree xclip
  - make setup_gpg
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - sudo pip install tox coveralls
before_script:
  - Xvfb :99 &
  - export DISPLAY=:99.0
script:
  - tox -e $TOX_ENV
after_success:
  - if [ "$TOX_ENV" == "coverage" ] ; then coveralls; fi
notifications:
  email: false
